### PR TITLE
Added support for loading ROM files from Lua script on Linux

### PR DESCRIPTION
**Pull request by randomCharacter**

### CODE REVIEW

**Comment by mjbudd77** [comment]
Looks good except that I think that LoadGame should be called instead of FCEUI_LoadGame as there are a few other things that need to be initialized in the SDL port when a Rom is loaded.

**Comment by randomCharacter** [comment]
Yes, I initially did that, but I switched to FCEUI_LoadGame because LoadGame was causing message box to appear. I guess this could be solved by adding optional silent parameter to LoadGame function as well. What do you think?

**Comment by mjbudd77** [comment]
That would be fine with me. Agree with making that argument optional.

**Comment by randomCharacter** [comment]
Updated PR. Do you want me to sent it to https://github.com/TASVideos/fceux directly?

**Comment by mjbudd77** [comment]
Can you send it to my personal fork? I will merge it later tonight if it passes the tests

**Comment by randomCharacter** [comment]
Sure.

**Pull request closed without merging**
